apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-shipping-deployment
spec:
  selector:
    matchLabels:
      app: front-end-shipping
  replicas: 3
  template:
    metadata:
      labels:
        app: front-end-shipping
    spec:
      containers:
      - name: front-end-shipping
        image:  epacthechnologies/front-end-shipping:v1
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__ProductsContext
            valueFrom:
              configMapKeyRef:
                name: mssql-connection-configmap
                key: db-connection-string
        #     secretKeyRef:
        #       name: mssql-secret
        #       key: db-connection-string-secret
---
kind: Service
apiVersion: v1
metadata:
  name: front-end-shipping-service
spec:
  selector:
    app: front-end-shipping
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer #NodePort
